### ISSUE TITLE
Integrate sleep / wake notifications?

### ISSUE THREAD

**Issue by mdbraber** [jaredks/rumps#108]
I'm building a radio player using rumps (https://github.com/mdbraber/radiobar). I'd like to catch relevant sleep / wake notifications to stop playing when my Macbook goes to sleep. An example implementation of what I'm looking for is described here:
https://stackoverflow.com/questions/31091413/how-to-best-catch-sleep-and-resume-events-for-osx (using `NSWorkspaceWillSleepNotifaction` and `NSWorkspaceDidWakeNotification` from AppKit)

Would it be possible to integrate this into rumps?

**Comment by mdbraber** [comment]
I've created a possible PR  #109

**Comment by jaredks** [comment]
https://github.com/jaredks/rumps/pull/109
