### ISSUE TITLE
Is it possible to update icon in status bar?

### ISSUE THREAD

**Issue by mountwebs** [jaredks/rumps#119]
Hi! Is it possible to update the icon in the status bar? I am trying to make an app that updates the icon every x seconds, but I can't make it work. Help is much appreciated!

**Comment by jaredks** [comment]
Definitely! Try this,

```python
import rumps

app = rumps.App('Test Change Icon', ':)')

@rumps.timer(2)
def change(_):
    app.title = ':(' if app.title == ':)' else ':)'

app.run()
```
