### ISSUE TITLE
What's the best way yo save preferences?

### ISSUE THREAD

**Issue by ckissi** [jaredks/rumps#121]
I would like to save preferences (eg. API key), What's the best way to do that?

**Comment by luckman212** [comment]
Not affiliated with rumps, but I'd think [plistlib](https://docs.python.org/3/library/plistlib.html) would be a good place to start.

**Comment by jaredks** [comment]
`rumps` doesn't enforce any particular method on saving preferences. At the moment, it only provides [`App.open`](https://rumps.readthedocs.io/en/latest/App.html#rumps.App.open) which is simply a convenience to open a file in application support folder for the app. You can of course save any type of preference file, anywhere.
