### ISSUE TITLE
No keyboard input in window possible

### ISSUE THREAD

**Issue by clee1994** [jaredks/rumps#127]
Hey Rumps Team, 

I am using macOS Catalina 10.15.1 and rumps==0.3.0. Whenever I use a rumps window (rumps.Window) the window shows but I cannot type into the text field. When running rumps from ipython the text goes straight into ipython. However, I can click in the text field and right-click copy, paste and cut work. Any ideas why direct keyboard input doesn't work?

Many thanks and best,
Clemens

PS: My code can be found under https://github.com/clee1994/pomodoro/blob/master/pomodoro.py.

**Comment by datadavev** [comment]
Have you tried running with `pythonw` instead of `python`?

**Comment by clee1994** [comment]
I was using pyenv and that doesn't come with pythonw. However, I found: https://github.com/pyenv/pyenv/issues/99

And doing 

```
env PYTHON_CONFIGURE_OPTS="--enable-framework CC=clang" pyenv install 3.8.0
```

Using this python then solved my issue. 
Many thanks!
