### ISSUE TITLE
Can you upload 0.4.0 build to pypi?

### ISSUE THREAD

**Issue by lexygon** [jaredks/rumps#173]
Pypi doesn't contain the latest version and rumps currently doesn't work on `python 3.10` because the version `0.3.0` uses a direct import from `collections` for the class `Mapping` which should be imported it from `collections.abc` since `python 3.3` and as far as I see you already add a compat layer on the latest version but it is not existing on pypi.

I would like to help you by building and uploading it but of course I don't have an access to the package on pypi. 

Hope you will have some free time to handle this, good luck!

**Comment by mindaugasw** [comment]
This would be very welcome.
In the meantime it's possible to still use pip to install the latest version directly from GitHub:
`pip install git+https://github.com/jaredks/rumps@master`

**Comment by illegalbyte** [comment]
Had the same issue here, hopefully pypi can be updated soon.

**Comment by ivanoats** [comment]
Just a note to say you can put `git+https://github.com/jaredks/rumps@master` in requirements.txt in a line by itself, until this issue is resolved. 🙏

**Comment by jaredks** [comment]
✅
