### ISSUE TITLE
Timer no longer stops

### ISSUE THREAD

**Issue by misternate** [jaredks/rumps#176]
macOS Monterey; Python 3.9.9; rumps 0.3.0 and 0.40.
I am unable to stop or update timer object. Sanity checked against the [example_timers.py](https://github.com/jaredks/rumps/blob/master/examples/example_timers.py) and came across the same issue, where the timer cannot be stopped nor updated.

**Comment by jiayouzl** [comment]
There is something wrong with this code, and I also met it.

**Comment by daredoes** [comment]
Are these intel or M1 Chips?

**Comment by jaredks** [comment]
So I don't remember my thought when I originally wrote that example script but it's misleading to say the least.

There are actually two timers, one that is created with `@rumps.timer(1)` and another that is created with `rumps.Timer(a, 4)`. The controls in the menu are for the latter and they *do* work. You must start the timer before you can stop it or see an effect from changing the interval. All the while, the first timer is not effected by any of these manipulations. Once you click "Start timer", you can then click "All timers" and see that there are two separate ones. It looks like this:

```
[<Timer: [callback: 'a'; interval: 1; status: ON]>, <Timer: [callback: 'a'; interval: 4; status: ON]>]
```
