### ISSUE TITLE
Basic test app rumps.clicked not working

### ISSUE THREAD

**Issue by NikiLentz** [jaredks/rumps#186]
Hi,
I am using python 3.9.12 and am on the newest Monterey Update on M1Pro.

I have created a very basic example app
```

import rumps
class TestApp(object):
    def __init__(self):
        self.app = rumps.App("Test", title="🤨")
        self.menu = [rumps.MenuItem('Test123')]
    @rumps.clicked("Test123")
    def test_23(self, _):
        print("TEST")
    def run(self):
        self.app.run()
if __name__ == '__main__':
    TestApp().run()
```

I can't get anything to show up in the terminal after clicking Test123, I also tried notifications and opening a window and basically nothing seems to be called in the test_23 method when clicking.

**Comment by NikiLentz** [comment]
Ok, i just realised that it works when setting the callback explicitly in the self.menu constructor, is that how it's supposed to work?

**Comment by jaredks** [comment]
Yes because you are creating a `MenuItem` implicitly with the `clicked` call so by also creating it in `__init__`, they collided.
