### ISSUE TITLE
Mac M1 issue

### ISSUE THREAD

**Issue by andypoo79** [jaredks/rumps#199]
I'm currently using the MacBook Pro with the M1 chip and the code and using existing working code from my intel Mac, 
I can no longer get rumps to display on the top bar. Has anyone else seen this issue?

There are no errors or warnings In the debugger

**Comment by mindaugasw** [comment]
Adding more details and code that you're running would be useful. I'm using it on Macbook Pro M1 as well and have no issues, everything is working as expected.

**Comment by andypoo79** [comment]
I'm running the example from the top of the readme

import rumps

class AwesomeStatusBarApp(rumps.App):
    @rumps.clicked("Preferences")
    def prefs(self, _):
        rumps.alert("jk! no preferences available!")

    @rumps.clicked("Silly button")
    def onoff(self, sender):
        sender.state = not sender.state

    @rumps.clicked("Say hi")
    def sayhi(self, _):
        rumps.notification("Awesome title", "amazing subtitle", "hi!!1")

if __name__ == "__main__":
    AwesomeStatusBarApp("Awesome App").run()


Im running a M1 MacBook Pro 16gb with Ventura 13.2 OS version


it runs but I don't get anything. I might need to remove and reinstall everything.

I have checked the notifications are allowed from python, are there any other system setting that could affect rumps?

Many thanks

**Comment by andypoo79** [comment]
I have just run an app that uses rumps from the bottom of the readme with no issues, therefore my python install must be the issue. I will close this now, thank you for your input
