### ISSUE TITLE
How to create icon for the menu that changes white/black

### ISSUE THREAD

**Issue by esseti** [jaredks/rumps#206]
Hi all, 
how should I create the icon that goes in the menu bar so it adapts as the others?
right now, the other apps (e.g. docker) is either white or black depending on the wallpaper. 

![image](https://github.com/jaredks/rumps/assets/1928354/303f2c5f-df0c-4342-9617-87af0aa72f45)
![image](https://github.com/jaredks/rumps/assets/1928354/a6e6e3e5-cee1-4031-ad96-2ab6da6704b5)

how can I do the same here? is that possible?
or is there a format of icons that i should use?

**Comment by mindaugasw** [comment]
Set `template` argument when initializing the app: `rumps.App(template=True)`.

See documentation: https://rumps.readthedocs.io/en/latest/App.html#rumps.App.template

**Comment by knurl** [comment]
As the [previous post](https://github.com/jaredks/rumps/issues/206#issuecomment-1651491860) says, you need to use the template argument. This solved it for me. This issue should probably be closed.
