### ISSUE TITLE
start on login?

### ISSUE THREAD

**Issue by puterleat** [jaredks/rumps#29]
Is it possible to have a rumps menu item start on user login?

**Comment by lhl** [comment]
I assume once you turn it into an app w/ py2app you should be able to just drag the resulting app as a normal startup item.

**Comment by puterleat** [comment]
I guess so... I just wondered if there was a  way to do it programatically because apps like Dropbox etc do that... most people don't know how to manually make it start at login.

**Comment by lhl** [comment]
You could try an installer:
http://crushbeercrushcode.org/2014/01/using-pkgbuild-and-productbuild-on-os-x-10-7/

or scripting it:
http://stackoverflow.com/questions/14616553/add-py2app-application-to-osx-login-items

**Comment by puterleat** [comment]
ah - thanks.. that's obviously the way to do it.

**Comment by ChillarAnand** [comment]
Since most of the menubar apps are meant to be run at login, is there any plans to integrate start on login feature with rumps?
