### ISSUE TITLE
Default sender state.

### ISSUE THREAD

**Issue by kobzar** [jaredks/rumps#54]
Hi. 
Thanks for your job. Its really awesome library.
But i cant find how to resolve next question.
I would like make menu with next structure:
"Settings" => "One"
                      "Two"
                      "...."
With active sender state by default (with active check box). 
How i can do this? 
<img width="218" alt="screen shot 2016-06-17 at 08 33 05" src="https://cloud.githubusercontent.com/assets/1912842/16141658/be85b786-3466-11e6-8ce4-08bb0a2b1b72.png">

**Comment by craig-davis** [comment]
As an example from the [example class](https://github.com/jaredks/rumps/blob/master/examples/example_class.py#L4-L6). (Untested code, but should be close)
```
def __init__(self):
        super(AwesomeStatusBarApp, self).__init__("Awesome App")
        button = rumps.MenuItem("Silly button")
        button.state = 1
        self.menu = ["Preferences", button, "Say hi"]```
