### ISSUE TITLE
NameError: global name 'basestring' and 'unicode' is not defined (python 3)

### ISSUE THREAD

**Issue by avallete** [jaredks/rumps#57]
When I try to declare an App using python 3, an exception is thrown because of the function _require_string.

```
    145 def _require_string(*objs):
    146     for obj in objs:
--> 147         if not isinstance(obj, basestring):
    148             raise TypeError('a string is required but given {0}, a {1}'.format(obj, type(obj).__name__))
    149 

NameError: name 'basestring' is not defined
```

I have made some code to fix the issue here: https://github.com/jaredks/rumps/pull/58

**Comment by croqaz** [comment]
+1

**Comment by jaredks** [comment]
[Fixed with Python 3 support](https://github.com/jaredks/rumps/commit/6e4f469bfa6bb9f018522faf0a819fcef3f2a0bd).
