### ISSUE TITLE
Package on PyPI does not reflect latest version available on this repo

### ISSUE THREAD

**Issue by half0wl** [jaredks/rumps#60]
The current version on [PyPI](https://pypi.python.org/pypi/rumps/0.2.1a) (rumps==0.2.1a0) does not reflect the latest version with Python 3 support available on this repo. The version number appears to be the same as installing from source with `python setup.py install` (0.2.1a0), but they're not.

**Comment by jaredsuttles** [comment]
Bumped version and published 0.2.2 to PyPI

**Comment by jaredks** [comment]
Bumped version and published 0.2.2 to PyPI.
