### ISSUE TITLE
Slider in menu

### ISSUE THREAD

**Issue by mi-kas** [jaredks/rumps#61]
Ist there a way to implement such a slider with rumps?
![screen shot 2017-03-16 at 20 30 55](https://cloud.githubusercontent.com/assets/3816690/24015521/02e6d2ea-0a89-11e7-80ee-60bdb4f803e1.JPG)

**Comment by mitchmcdee** [comment]
Will attempt this some time this week hopefully :)

**Comment by mitchmcdee** [comment]
https://github.com/jaredks/rumps/pull/62

**Comment by mitchmcdee** [comment]
@jaredks PTAL

**Comment by jaredks** [comment]
https://github.com/jaredks/rumps/pull/101
