### ISSUE TITLE
More complex menus

### ISSUE THREAD

**Issue by rucuriousyet** [jaredks/rumps#68]
Is it possible to create menus with submenus or tree like structures? Also would be great if it was possible to add icons like those shown in the image.
<img width="276" alt="screen shot 2017-06-17 at 5 32 30 pm" src="https://user-images.githubusercontent.com/8526984/27256453-fb9c06a2-5382-11e7-9e48-4e8cb9274770.png">

**Comment by daredoes** [comment]
I'm not sure when, but I believe all of these features were added to rumps. [Use add on a menuitem](https://rumps.readthedocs.io/en/latest/MenuItem.html#rumps.MenuItem.add) to create a submenu, or tree like structure.

**Comment by jaredks** [comment]
```python
import rumps

app = rumps.App('thing')

first = rumps.MenuItem('first', key='a')
@first.set_callback
def cb(sender):
  pass

second = rumps.MenuItem('second', key='B')
second.update(['1', '2'])
@second.set_callback
def cb(sender):
  pass

app.menu = [first, second]

app.run()
```
