### ISSUE TITLE
Python3 ModuleNotFoundError: No module named 'rumps'

### ISSUE THREAD

**Issue by Neo93** [jaredks/rumps#73]
I'm using Python3 and installed rumps via pip3 but I get the no module named 'rumps' error.

Someone has an idea?

**Comment by L3rchal** [comment]
Hmm check `/usr/local/lib/python3.6/site-packages` and with ls -tr would check latest package if rumps is not there something went wrong with installation and would try use pip3 with -v (would recommend anyway). If package is there then I don't know why you can't import it.

Also I would try use ```python3 -m pip install rumps``` maybe that would install rumps for python3.

**Comment by daredoes** [comment]
@Neo93 if you're still having this issue, can you provide the output of `pip3 freeze` to this thread?

**Comment by jaredks** [comment]
Hopefully this got resolved but it doesn't seem like a rumps issue.
