### ISSUE TITLE
README should link to other people's project that have screenshots

### ISSUE THREAD

**Issue by paul-hammant** [jaredks/rumps#77]
All these have screenshots and are sufficiently different to list on your README.

https://github.com/OzTamir/WhyFi/
https://github.com/dougn/HalfCaff
https://github.com/Bucknalla/attendee-tool-mlh
https://github.com/josepvalls/rideindegochecker
https://github.com/jeffgodwyll/bundle-checker
https://github.com/asakasinsky/py-Timey
https://github.com/e9t/c1t1
https://github.com/snare/idiot
https://github.com/spalter/osx-bamboo-plan-status
https://github.com/helmholtz/narcissist
https://github.com/yask123/SpotifyLyrics
https://github.com/Demonstrandum/WordTime
https://github.com/Egregors/pySplash
https://github.com/sogseal/Zero
https://github.com/damln/dns.app
https://github.com/chrisfosterelli/commitwatch
https://github.com/kenkeiter/allofthelights
https://github.com/sarkkine/sonostus
https://github.com/Sayan98/cryptocoin-quotes
https://github.com/L3rchal/WallpDesk
https://github.com/vekkt0r/harmenubar
https://github.com/mejmo/mac-shrew
https://github.com/jamfit/HipStatus
https://github.com/ericwb/slack-status-bar
https://github.com/mankoff/umma

**Comment by L3rchal** [comment]
Nice thanks for info, look on the other projects for inspiration. Btw how did you found all these projects? 

@jaredks please add this to readme I am sure others will welcome done solutions

**Comment by paul-hammant** [comment]
Used Github's search for "import rumps" and spend an hour advancing through pages of it.  I was considering **not** using rumps. Now I've seen all the above, I'm going to use it. Fingers crossed there is something as smooth for Windows and Linux.

**Comment by daredoes** [comment]
This last has been added to the readme in PR #91

**Comment by jaredks** [comment]
@paul-hammant Thank you for compiling this list!

**Comment by jaredks** [comment]
https://github.com/jaredks/rumps/pull/91
