### ISSUE TITLE
Can't type any string in windows and doesn't display on top.

### ISSUE THREAD

**Issue by grtfou** [jaredks/rumps#84]
I design a simple pop window. But..
  * The window doesn't display on top level, it behinds others.
  * I can't use keyboard to type any string in textarea.

```python
@rumps.clicked("Setting")
def area_setting(self, sender):
    setting_window = rumps.Window(
        message='msg',
        title='Preferences',
        default_text="input in here",
        ok="Submit",
        cancel='Cancel',
        dimensions=(100, 20)
    )
    resp = setting_window.run()
    if resp.clicked:
        print(resp.text) 
```

  * Python == 3.6
  * rumps == 0.2.2
  * OS X == 10.13.3

Thanks.

**Comment by zbot473** [comment]
+1

**Comment by daredoes** [comment]
Hello @zbot473 @grtfou !

I'm not sure what the solution to the problem is for execution in an IDE, but I do know a workaround.

The workaround is to export the code using py2app, and test it out there. The information for how to do that can be found on the README. 

Definitely a hassle, but @jaredks and I are now aware of this issue. If anyone has insights on a solution to this problem, pull requests and discussions are appreciated!

**Comment by jaredks** [comment]
It looks like this is a problem with `virtualenv`. It isn't mentioned here, but I'm assuming that is what @grtfou was using (I was also).

So something like this will as leave the window behind others and not allow certain UI interactions,

```
virtualenv env --python=python3
```

If you instead use `venv` packaged with Python 3,

```
python3 -m venv env
```

it works. It looks like the reason for this is how `virtualenv` copies the executable. It is explained well here https://github.com/pypa/virtualenv/issues/322.

When already created, I'm not sure there will be any clean way to get it to function properly.

**Comment by grtfou** [comment]
Yes. I use [pyenv](https://github.com/pyenv/pyenv) to build my virtual environment.

I setup `py2app` fail in my computer. So I can't try `py2app` solution.
So I followed @jaredks idea, try to fix virtualenv problem.

Then...It's work. The issue is virtualenv problem. :)

```bash
# Build a new virtualenv
$ CFLAGS="-I$(brew --prefix readline)/include -I$(brew --prefix openssl)/include -I$(xcrun --show-sdk-path)/usr/include" \
LDFLAGS="-L$(brew --prefix readline)/lib -L$prefix openssl)/lib" \
PYTHON_CONFIGURE_OPTS="--enable-unicode=ucs2 --enable-framework" \
pyenv install -v 3.6.4

$ python -V
3.6.4
$ pip install rumps
$ python myapp.py            # It's work
```

Thanks for @daredoes and @jaredks help.

ref:
  * /pyenv/pyenv/issues/1219
  * /pyenv/pyenv/issues/1095

**Comment by grtfou** [comment]
```bash
$ CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" \
    PYTHON_CONFIGURE_OPTS="--enable-unicode=ucs2 --enable-framework" \
    pyenv install -v 3.7.3
```

**Comment by jaredks** [comment]
@grtfou Are you able to test https://github.com/jaredks/rumps/pull/117? It's an ugly hack but it does allow interaction for me.

**Comment by grtfou** [comment]
Sure. 🤔

I test it. It's work for me.
  * MacOS: 10.14.4
  * Python: 3.7.0

p.s. If `pyenv` setup before, It should be remove to keep `python` command is native.

```bash
$ python3 -m venv myenv
$ source myenv/bin/activate
$ (myenv) git clone https://github.com/jaredks/rumps.git
$ (myenv) cd rumps
$ (myenv) git checkout e4d48c0
$ (myenv) python setup install
$ (myenv) pip freeze
pyobjc-core==5.2
pyobjc-framework-Cocoa==5.2
rumps==0.3.0.dev0

$ (myenv) which python
/Users/<my_path>/myenv/bin/python

$ (myenv) python my_app.py      # it's work
```

**Comment by jaredks** [comment]
@grtfou Thanks!
