### ISSUE TITLE
callback not being triggered

### ISSUE THREAD

**Issue by amloewi** [jaredks/rumps#85]
I have a very simple app

    class AwesomeStatusBarApp(rumps.App):
        @rumps.clicked("Play")
        def mg(self, callback=minigame, key='y'): 
            minigame()

where the minigame is a small pygame script. It runs fine when I select it from the menubar, but I can't get the hotkey to work. Additionally, the shortcut doesn't even show up in the menubar unless I add a MenuItem separately -- but then that menu item does NOT trigger the callback, even when selected from the menu.

MacOS 10.13.5, Anaconda Python 3.6.5

**Comment by daredoes** [comment]
As shown in [the docs](https://rumps.readthedocs.io/en/latest/clicked.html#rumps.clicked) the codeblock should be

```
class AwesomeStatusBarApp(rumps.App):
    @rumps.clicked("Play", key='y')
    def mg(self, _): 
        minigame()
```
