### ISSUE TITLE
Not A Code Issue

### ISSUE THREAD

**Issue by daredoes** [jaredks/rumps#86]
@jaredks I am attempting to reach you to help with the maintenance of this repository, or to at least alert you that it needs some love. 

I would be happy to offer my time as a collaborator on the repo to support the community that loves this project.

**Comment by brooksc** [comment]
@daredoes I saw your note after looking to see if there were any other forks being maintained.

After some poking around I suspect https://www.linkedin.com/in/jaredsuttles/ is Jaredks.  I have linkedin premium at the moment so I'll ping him and ask him to check this issue.

**Comment by daredoes** [comment]
@brooksc yeah, I found that and reached out via email to the company he works at since I don't have premium. Hope it goes well!
