### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'setDelegate_'

### ISSUE THREAD

**Issue by danisawesome** [jaredks/rumps#9]
When trying to run any of the examples, I'm running into this error:

Traceback (most recent call last):
  File "queue_client.py", line 57, in <module>
    app.run()
  File "/Users/danielschales/Envs/queue_client/lib/python2.7/site-packages/rumps/rumps.py", line 703, in run
    NSUserNotificationCenter.defaultUserNotificationCenter().setDelegate_(self._nsapp)
AttributeError: 'NoneType' object has no attribute 'setDelegate_'

This is on a fresh install of Mavericks 10.9.1, using Homebrew installed Python 2.7.6, and installed PyObjC using pip all in a virtualenv. Using tito's fork as well as the official rumps repo. It was working in my previous Mavericks installation, but the system Python install was a mess, hence the reinstall and usage of a virtualenv this time around.

**Comment by kjagiello** [comment]
+1

**Comment by RyanBalfanz** [comment]
+1

Encountered this after #12 and #21

**Comment by goodes** [comment]
+1

**Comment by toddwilson** [comment]
+1

**Comment by vink007** [comment]
+1

**Comment by scoates** [comment]
+1

**Comment by scoates** [comment]
FWIW, if I check out rumps manually and run some code from within the git checkout (read: if I don't use the `pip`-installed rumps), it works as expected.

**Comment by tvalliersbu** [comment]
+!

**Comment by mlsptn** [comment]
+1

**Comment by RyanBalfanz** [comment]
@scoates, As of now, there're 6 commits to master since [v0.2.0](624104adb65a71b8984d74e17cc2fe8aec7fe8e2) was released so you may be right. @jaredks, can you verify and push a new release to PyPI?

**Comment by aerickson** [comment]
+1 on this... would love to get it working. 

Is there a pyobjc bug filed? 

@jaredks Where does the fix you mentioned go? Thanks for making this project. :)

**Comment by gotlium** [comment]
+1

**Comment by zollman** [comment]
This appears to have something to do with the difference in plist file from the main python and virtualenv python:

    mybox:rumps-test user$ ls -l /usr/bin/python
    -rwxr-xr-x  2 root  wheel  58608 May 20  2014 /usr/bin/python
    (virtualenv)mybox:rumps-test user$ ls -l `which python`
    -rwxr-xr-x  1 user  staff  34592 Apr 19 15:39 /Users/user/src/collector/virtualenv/bin/python

If I manually copy /usr/bin/python into my virtualenv, then this code snippet starts working (i.e., returns something other than None):

    from Foundation import NSUserNotificationCenter
    NSUserNotificationCenter.defaultUserNotificationCenter()

However, I don't know MacOS at all to know how to associate a plist file with my virtualenv. Any further ideas?

**Comment by mankoff** [comment]
@zollman confirming your fix works for me. I'm using the Anaconda (scientific) python from Continuum. Oddly `ipython simple_example.py` worked, but `python simple_example.py` did not. Adding the `Info.plist` to the `anaconda/bin/` folder worked, or installing `rumps` from your `bugfix-nobundleid` branch works too. Thank you!

**Comment by zollman** [comment]
Note for those browsing this: I closed my pull request -- while it prevents the specific error from being thrown, a dynamically-generated Plist won't actually give you the ability to throw real notifications on OS X. Works for the other use cases though.

**Comment by zefijsd** [comment]
+1

**Comment by etiology** [comment]
+1

**Comment by abyx** [comment]
+1

**Comment by jdp** [comment]
+1

**Comment by sabativi** [comment]
+1

**Comment by norcalli** [comment]
+1

**Comment by chrisfosterelli** [comment]
+1

**Comment by kennethreitz** [comment]
+1

**Comment by wddwycc** [comment]
+1

**Comment by jaredks** [comment]
Fix published to PyPI

**Comment by kennethreitz** [comment]
\o/

**Comment by kennethreitz** [comment]
thank you @jaredks! Really looking forward to playing with this software now!
